"use client";

import { useState, useEffect } from "react";
import { X, Copy, Download, Check, FileText, Loader2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { jsPDF } from "jspdf";

interface DisputeLetterModalProps {
  letter: string;
  onClose: () => void;
}

export function DisputeLetterModal({ letter, onClose }: DisputeLetterModalProps) {
  const [copied, setCopied] = useState(false);
  const [mounted, setMounted] = useState(false);
  const [isGeneratingPdf, setIsGeneratingPdf] = useState(false);

  useEffect(() => {
    setMounted(true);
  }, []);

  const handleCopy = async () => {
    await navigator.clipboard.writeText(letter);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadPdf = async () => {
    setIsGeneratingPdf(true);
    
    try {
      const doc = new jsPDF({
        orientation: "portrait",
        unit: "mm",
        format: "a4",
      });

      // Set up fonts and colors
      const pageWidth = doc.internal.pageSize.getWidth();
      const pageHeight = doc.internal.pageSize.getHeight();
      const margin = 20;
      const maxWidth = pageWidth - margin * 2;
      let yPosition = margin;

      // Add header
      doc.setFillColor(24, 24, 27); // zinc-900
      doc.rect(0, 0, pageWidth, 35, "F");
      
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(18);
      doc.setFont("helvetica", "bold");
      doc.text("Medical Bill Dispute Letter", margin, 22);
      
      doc.setFontSize(9);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(161, 161, 170); // zinc-400
      doc.text(`Generated by BillAnalyzer | ${new Date().toLocaleDateString()}`, margin, 30);

      yPosition = 50;

      // Add content
      doc.setTextColor(39, 39, 42); // zinc-800
      doc.setFontSize(11);
      doc.setFont("helvetica", "normal");

      // Split text into lines that fit within the page width
      const lines = doc.splitTextToSize(letter, maxWidth);
      
      for (const line of lines) {
        // Check if we need a new page
        if (yPosition > pageHeight - margin) {
          doc.addPage();
          yPosition = margin;
        }
        
        doc.text(line, margin, yPosition);
        yPosition += 6;
      }

      // Add footer on last page
      const footerY = pageHeight - 15;
      doc.setDrawColor(228, 228, 231); // zinc-200
      doc.line(margin, footerY - 5, pageWidth - margin, footerY - 5);
      
      doc.setFontSize(8);
      doc.setTextColor(161, 161, 170);
      doc.text("This document was generated by BillAnalyzer - Medical Bill Auditing Platform", margin, footerY);
      doc.text("www.billanalyzer.com", pageWidth - margin, footerY, { align: "right" });

      // Save the PDF
      doc.save("dispute-letter.pdf");
    } catch (error) {
      console.error("Error generating PDF:", error);
    } finally {
      setIsGeneratingPdf(false);
    }
  };

  return (
    <div 
      className={`fixed inset-0 bg-black/90 backdrop-blur-sm flex items-center justify-center z-50 p-4 transition-opacity duration-300 ${mounted ? 'opacity-100' : 'opacity-0'}`}
      onClick={(e) => e.target === e.currentTarget && onClose()}
    >
      <div className={`bg-zinc-900 rounded-2xl max-w-2xl w-full max-h-[85vh] flex flex-col border border-zinc-800/50 shadow-2xl transition-all duration-300 ${mounted ? 'scale-100 opacity-100' : 'scale-95 opacity-0'}`}>
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-5 border-b border-zinc-800/50">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 bg-green-500/10 rounded-xl flex items-center justify-center">
              <FileText className="w-5 h-5 text-green-500" />
            </div>
            <div>
              <h2 className="text-lg font-semibold text-white">
                Dispute Letter Generated
              </h2>
              <p className="text-xs text-zinc-500">Ready to send to your provider</p>
            </div>
          </div>
          <button
            type="button"
            onClick={onClose}
            className="w-8 h-8 flex items-center justify-center rounded-lg text-zinc-500 hover:text-white hover:bg-zinc-800 transition-all"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Content */}
        <div className="flex-1 overflow-auto p-6">
          <div className="bg-zinc-950/50 rounded-xl border border-zinc-800/50 p-6">
            <pre className="text-sm text-zinc-300 whitespace-pre-wrap font-mono leading-relaxed">
              {letter}
            </pre>
          </div>
        </div>

        {/* Footer */}
        <div className="flex items-center justify-between px-6 py-5 border-t border-zinc-800/50 bg-zinc-900/50">
          <p className="text-xs text-zinc-600">{letter.length} characters</p>
          <div className="flex items-center gap-3">
            <Button
              variant="outline"
              onClick={handleCopy}
              className="border-zinc-700 text-white hover:bg-zinc-800/50 bg-transparent transition-all"
            >
              {copied ? (
                <>
                  <Check className="w-4 h-4 mr-2 text-green-500" />
                  Copied!
                </>
              ) : (
                <>
                  <Copy className="w-4 h-4 mr-2" />
                  Copy
                </>
              )}
            </Button>
            <Button
              onClick={handleDownloadPdf}
              disabled={isGeneratingPdf}
              className="bg-white text-black hover:bg-zinc-200 transition-all disabled:opacity-50"
            >
              {isGeneratingPdf ? (
                <>
                  <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                  Generating...
                </>
              ) : (
                <>
                  <Download className="w-4 h-4 mr-2" />
                  Download PDF
                </>
              )}
            </Button>
          </div>
        </div>
      </div>
    </div>
  );
}
